/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcknowledgeJobRequest
 */
export interface AcknowledgeJobRequest {
    /**
     * 
     * @type {string}
     * @memberof AcknowledgeJobRequest
     */
    jobExecutionId: string;
}

/**
 * Check if a given object implements the AcknowledgeJobRequest interface.
 */
export function instanceOfAcknowledgeJobRequest(value: object): value is AcknowledgeJobRequest {
    if (!('jobExecutionId' in value) || value['jobExecutionId'] === undefined) return false;
    return true;
}

export function AcknowledgeJobRequestFromJSON(json: any): AcknowledgeJobRequest {
    return AcknowledgeJobRequestFromJSONTyped(json, false);
}

export function AcknowledgeJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcknowledgeJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jobExecutionId': json['jobExecutionId'],
    };
}

export function AcknowledgeJobRequestToJSON(value?: AcknowledgeJobRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobExecutionId': value['jobExecutionId'],
    };
}

