/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetNextJobs200ResponseJobExecutionInner
 */
export interface GetNextJobs200ResponseJobExecutionInner {
  /**
   * The job ID
   * @type {string}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  jobAgentId: string;
  /**
   *
   * @type {object}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  jobAgentConfig: object;
  /**
   *
   * @type {string}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof GetNextJobs200ResponseJobExecutionInner
   */
  jobConfigId: string;
}

/**
 * Check if a given object implements the GetNextJobs200ResponseJobExecutionInner interface.
 */
export function instanceOfGetNextJobs200ResponseJobExecutionInner(
  value: object
): value is GetNextJobs200ResponseJobExecutionInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("jobAgentId" in value) || value["jobAgentId"] === undefined)
    return false;
  if (!("jobAgentConfig" in value) || value["jobAgentConfig"] === undefined)
    return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("jobConfigId" in value) || value["jobConfigId"] === undefined)
    return false;
  return true;
}

export function GetNextJobs200ResponseJobExecutionInnerFromJSON(
  json: any
): GetNextJobs200ResponseJobExecutionInner {
  return GetNextJobs200ResponseJobExecutionInnerFromJSONTyped(json, false);
}

export function GetNextJobs200ResponseJobExecutionInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetNextJobs200ResponseJobExecutionInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    status: json["status"],
    jobAgentId: json["jobAgentId"],
    jobAgentConfig: json["jobAgentConfig"],
    message: json["message"],
    jobConfigId: json["jobConfigId"],
  };
}

export function GetNextJobs200ResponseJobExecutionInnerToJSON(
  value?: GetNextJobs200ResponseJobExecutionInner | null
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    status: value["status"],
    jobAgentId: value["jobAgentId"],
    jobAgentConfig: value["jobAgentConfig"],
    message: value["message"],
    jobConfigId: value["jobConfigId"],
  };
}
