/* tslint:disable */
/* eslint-disable */
/**
 * Target Provider API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProviderByName200Response
 */
export interface GetProviderByName200Response {
    /**
     * 
     * @type {string}
     * @memberof GetProviderByName200Response
     */
    id?: string;
}

/**
 * Check if a given object implements the GetProviderByName200Response interface.
 */
export function instanceOfGetProviderByName200Response(value: object): value is GetProviderByName200Response {
    return true;
}

export function GetProviderByName200ResponseFromJSON(json: any): GetProviderByName200Response {
    return GetProviderByName200ResponseFromJSONTyped(json, false);
}

export function GetProviderByName200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProviderByName200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetProviderByName200ResponseToJSON(value?: GetProviderByName200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

