/* tslint:disable */
/* eslint-disable */
/**
 * Deployment Targets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetScannerByName200Response
 */
export interface GetScannerByName200Response {
    /**
     * 
     * @type {string}
     * @memberof GetScannerByName200Response
     */
    id?: string;
}

/**
 * Check if a given object implements the GetScannerByName200Response interface.
 */
export function instanceOfGetScannerByName200Response(value: object): value is GetScannerByName200Response {
    return true;
}

export function GetScannerByName200ResponseFromJSON(json: any): GetScannerByName200Response {
    return GetScannerByName200ResponseFromJSONTyped(json, false);
}

export function GetScannerByName200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetScannerByName200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetScannerByName200ResponseToJSON(value?: GetScannerByName200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

