/* tslint:disable */
/* eslint-disable */
/**
 * Target Provider API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTargetProviderByName200Response
 */
export interface GetTargetProviderByName200Response {
    /**
     * 
     * @type {string}
     * @memberof GetTargetProviderByName200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetTargetProviderByName200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetTargetProviderByName200Response
     */
    workspaceId: string;
}

/**
 * Check if a given object implements the GetTargetProviderByName200Response interface.
 */
export function instanceOfGetTargetProviderByName200Response(value: object): value is GetTargetProviderByName200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    return true;
}

export function GetTargetProviderByName200ResponseFromJSON(json: any): GetTargetProviderByName200Response {
    return GetTargetProviderByName200ResponseFromJSONTyped(json, false);
}

export function GetTargetProviderByName200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTargetProviderByName200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'workspaceId': json['workspaceId'],
    };
}

export function GetTargetProviderByName200ResponseToJSON(value?: GetTargetProviderByName200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'workspaceId': value['workspaceId'],
    };
}

