/* tslint:disable */
/* eslint-disable */
/**
 * Target Provider API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetProvidersTargetsRequestTargetsInner } from './SetProvidersTargetsRequestTargetsInner';
import {
    SetProvidersTargetsRequestTargetsInnerFromJSON,
    SetProvidersTargetsRequestTargetsInnerFromJSONTyped,
    SetProvidersTargetsRequestTargetsInnerToJSON,
} from './SetProvidersTargetsRequestTargetsInner';

/**
 * 
 * @export
 * @interface SetProvidersTargetsRequest
 */
export interface SetProvidersTargetsRequest {
    /**
     * 
     * @type {Array<SetProvidersTargetsRequestTargetsInner>}
     * @memberof SetProvidersTargetsRequest
     */
    targets?: Array<SetProvidersTargetsRequestTargetsInner>;
}

/**
 * Check if a given object implements the SetProvidersTargetsRequest interface.
 */
export function instanceOfSetProvidersTargetsRequest(value: object): value is SetProvidersTargetsRequest {
    return true;
}

export function SetProvidersTargetsRequestFromJSON(json: any): SetProvidersTargetsRequest {
    return SetProvidersTargetsRequestFromJSONTyped(json, false);
}

export function SetProvidersTargetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetProvidersTargetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targets': json['targets'] == null ? undefined : ((json['targets'] as Array<any>).map(SetProvidersTargetsRequestTargetsInnerFromJSON)),
    };
}

export function SetProvidersTargetsRequestToJSON(value?: SetProvidersTargetsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'targets': value['targets'] == null ? undefined : ((value['targets'] as Array<any>).map(SetProvidersTargetsRequestTargetsInnerToJSON)),
    };
}

