/* tslint:disable */
/* eslint-disable */
/**
 * Target Provider API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetProvidersTargetsRequestTargetsInner
 */
export interface SetProvidersTargetsRequestTargetsInner {
    /**
     * 
     * @type {string}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    provider: string;
    /**
     * 
     * @type {object}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    config: object;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SetProvidersTargetsRequestTargetsInner
     */
    labels: { [key: string]: string; };
}

/**
 * Check if a given object implements the SetProvidersTargetsRequestTargetsInner interface.
 */
export function instanceOfSetProvidersTargetsRequestTargetsInner(value: object): value is SetProvidersTargetsRequestTargetsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function SetProvidersTargetsRequestTargetsInnerFromJSON(json: any): SetProvidersTargetsRequestTargetsInner {
    return SetProvidersTargetsRequestTargetsInnerFromJSONTyped(json, false);
}

export function SetProvidersTargetsRequestTargetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetProvidersTargetsRequestTargetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        'kind': json['kind'],
        'provider': json['provider'],
        'config': json['config'],
        'labels': json['labels'],
    };
}

export function SetProvidersTargetsRequestTargetsInnerToJSON(value?: SetProvidersTargetsRequestTargetsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'version': value['version'],
        'kind': value['kind'],
        'provider': value['provider'],
        'config': value['config'],
        'labels': value['labels'],
    };
}

