/* tslint:disable */
/* eslint-disable */
/**
 * Deployment Targets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateDeploymentTargetByNameRequestConfigCluster } from './UpdateDeploymentTargetByNameRequestConfigCluster';
import {
    UpdateDeploymentTargetByNameRequestConfigClusterFromJSON,
    UpdateDeploymentTargetByNameRequestConfigClusterFromJSONTyped,
    UpdateDeploymentTargetByNameRequestConfigClusterToJSON,
} from './UpdateDeploymentTargetByNameRequestConfigCluster';

/**
 * 
 * @export
 * @interface UpdateDeploymentTargetByNameRequestConfig
 */
export interface UpdateDeploymentTargetByNameRequestConfig {
    /**
     * 
     * @type {string}
     * @memberof UpdateDeploymentTargetByNameRequestConfig
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeploymentTargetByNameRequestConfig
     */
    status?: string;
    /**
     * 
     * @type {UpdateDeploymentTargetByNameRequestConfigCluster}
     * @memberof UpdateDeploymentTargetByNameRequestConfig
     */
    cluster?: UpdateDeploymentTargetByNameRequestConfigCluster;
}

/**
 * Check if a given object implements the UpdateDeploymentTargetByNameRequestConfig interface.
 */
export function instanceOfUpdateDeploymentTargetByNameRequestConfig(value: object): value is UpdateDeploymentTargetByNameRequestConfig {
    return true;
}

export function UpdateDeploymentTargetByNameRequestConfigFromJSON(json: any): UpdateDeploymentTargetByNameRequestConfig {
    return UpdateDeploymentTargetByNameRequestConfigFromJSONTyped(json, false);
}

export function UpdateDeploymentTargetByNameRequestConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDeploymentTargetByNameRequestConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'cluster': json['cluster'] == null ? undefined : UpdateDeploymentTargetByNameRequestConfigClusterFromJSON(json['cluster']),
    };
}

export function UpdateDeploymentTargetByNameRequestConfigToJSON(value?: UpdateDeploymentTargetByNameRequestConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'status': value['status'],
        'cluster': UpdateDeploymentTargetByNameRequestConfigClusterToJSON(value['cluster']),
    };
}

