/* tslint:disable */
/* eslint-disable */
/**
 * Deployment Targets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDeploymentTargetByNameRequestConfigCluster
 */
export interface UpdateDeploymentTargetByNameRequestConfigCluster {
    /**
     * 
     * @type {string}
     * @memberof UpdateDeploymentTargetByNameRequestConfigCluster
     */
    certificateAuthorityData?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDeploymentTargetByNameRequestConfigCluster
     */
    endpoint?: string;
}

/**
 * Check if a given object implements the UpdateDeploymentTargetByNameRequestConfigCluster interface.
 */
export function instanceOfUpdateDeploymentTargetByNameRequestConfigCluster(value: object): value is UpdateDeploymentTargetByNameRequestConfigCluster {
    return true;
}

export function UpdateDeploymentTargetByNameRequestConfigClusterFromJSON(json: any): UpdateDeploymentTargetByNameRequestConfigCluster {
    return UpdateDeploymentTargetByNameRequestConfigClusterFromJSONTyped(json, false);
}

export function UpdateDeploymentTargetByNameRequestConfigClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDeploymentTargetByNameRequestConfigCluster {
    if (json == null) {
        return json;
    }
    return {
        
        'certificateAuthorityData': json['certificateAuthorityData'] == null ? undefined : json['certificateAuthorityData'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
    };
}

export function UpdateDeploymentTargetByNameRequestConfigClusterToJSON(value?: UpdateDeploymentTargetByNameRequestConfigCluster | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'certificateAuthorityData': value['certificateAuthorityData'],
        'endpoint': value['endpoint'],
    };
}

