/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateJobDispatcherRequest
 */
export interface UpdateJobDispatcherRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateJobDispatcherRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateJobDispatcherRequest
     */
    type: string;
}

/**
 * Check if a given object implements the UpdateJobDispatcherRequest interface.
 */
export function instanceOfUpdateJobDispatcherRequest(value: object): value is UpdateJobDispatcherRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UpdateJobDispatcherRequestFromJSON(json: any): UpdateJobDispatcherRequest {
    return UpdateJobDispatcherRequestFromJSONTyped(json, false);
}

export function UpdateJobDispatcherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateJobDispatcherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
    };
}

export function UpdateJobDispatcherRequestToJSON(value?: UpdateJobDispatcherRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
    };
}

