/* tslint:disable */
/* eslint-disable */
/**
 * Deployment Targets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1DeploymentTargetsPost200Response
 */
export interface V1DeploymentTargetsPost200Response {
    /**
     * 
     * @type {string}
     * @memberof V1DeploymentTargetsPost200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeploymentTargetsPost200Response
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeploymentTargetsPost200Response
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeploymentTargetsPost200Response
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeploymentTargetsPost200Response
     */
    name?: string;
    /**
     * 
     * @type {object}
     * @memberof V1DeploymentTargetsPost200Response
     */
    config?: object;
    /**
     * 
     * @type {object}
     * @memberof V1DeploymentTargetsPost200Response
     */
    labels?: object;
}

/**
 * Check if a given object implements the V1DeploymentTargetsPost200Response interface.
 */
export function instanceOfV1DeploymentTargetsPost200Response(value: object): value is V1DeploymentTargetsPost200Response {
    return true;
}

export function V1DeploymentTargetsPost200ResponseFromJSON(json: any): V1DeploymentTargetsPost200Response {
    return V1DeploymentTargetsPost200ResponseFromJSONTyped(json, false);
}

export function V1DeploymentTargetsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeploymentTargetsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'name': json['name'] == null ? undefined : json['name'],
        'config': json['config'] == null ? undefined : json['config'],
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

export function V1DeploymentTargetsPost200ResponseToJSON(value?: V1DeploymentTargetsPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'version': value['version'],
        'kind': value['kind'],
        'provider': value['provider'],
        'name': value['name'],
        'config': value['config'],
        'labels': value['labels'],
    };
}

